/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inventory.ui;
import com.inventory.model.Product;
import com.inventory.model.TransactionRecord;
import com.inventory.model.TransactionType;
import com.inventory.store.DataStore;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author djyim
 */
public class SaleFrame extends javax.swing.JFrame {
private final DataStore ds = com.inventory.store.AppState.DATA_STORE;

private void loadProductCombo() {
    cmbProducts.removeAllItems();

    ((javax.swing.JComboBox) cmbProducts).addItem("ทั้งหมด");

    for (com.inventory.model.Product p : ds.getProducts()) {
        ((javax.swing.JComboBox) cmbProducts).addItem(p);
    }
}
private void setupSaleTable() {
    tblSale.setModel(new DefaultTableModel(
        new Object[][]{},
        new String[]{"รหัสสินค้า", "ชื่อสินค้า", "จำนวน", "ราคาต่อหน่วย", "ราคารวม", "วันเวลา"}
    ));
}
private void loadSaleTable() {
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblSale.getModel();
    model.setRowCount(0);

    Object selected = cmbProducts.getSelectedItem();

    for (com.inventory.model.TransactionRecord r : ds.getTransactions()) {
        if (r.getType() == com.inventory.model.TransactionType.SALE) {

            
            if (selected == null || selected.toString().equals("ทั้งหมด")) {
                model.addRow(new Object[]{
                    r.getProductId(),
                    r.getProductName(),
                    r.getQuantity(),
                    r.getUnitPrice(),
                    r.getTotalPrice(),
                    r.getDateTime()
                });
            } 
            
            else {
                com.inventory.model.Product p = (com.inventory.model.Product) selected;

                if (r.getProductId() == p.getId()) {
                    model.addRow(new Object[]{
                        r.getProductId(),
                        r.getProductName(),
                        r.getQuantity(),
                        r.getUnitPrice(),
                        r.getTotalPrice(),
                        r.getDateTime()
                    });
                }
            }
        }
    }
}
private void clearForm() {
    txtQuantity.setText("");
    cmbProducts.setSelectedIndex(0); 
}
    /**
     * Creates new form SaleFrame
     */
    public SaleFrame() {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    tblSale.setFont(new java.awt.Font("Tahoma", 0, 14));
    tblSale.setRowHeight(25);
    tblSale.getTableHeader().setFont(new java.awt.Font("Tahoma", 1, 14));
    cmbProducts.setFont(new java.awt.Font("Tahoma", 0, 14));
    setupSaleTable();
    loadProductCombo();
    loadSaleTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbProducts = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        btnSaveSale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSale = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("หน้าขายสินค้า / ตัดสต๊อกอัตโนมัติ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("สินค้า");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("จำนวนสินค้า");

        cmbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductsActionPerformed(evt);
            }
        });

        btnSaveSale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveSale.setText("บันทึกสินค้า");
        btnSaveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveSale)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveSale))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSale);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ประวัติสินค้า");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSaleActionPerformed
       if (cmbProducts.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "กรุณาเลือกสินค้า");
        return;
    }

    try {
        Product selectedProduct = (Product) cmbProducts.getSelectedItem();
        int qty = Integer.parseInt(txtQuantity.getText().trim());

        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "จำนวนสินค้าต้องมากกว่า 0");
            return;
        }

        boolean success = ds.sellStock(selectedProduct.getId(), qty);

        if (success) {
            loadProductCombo();
            loadSaleTable();
            clearForm();
            JOptionPane.showMessageDialog(this, "บันทึกการขายสำเร็จ");
        } else {
            JOptionPane.showMessageDialog(this, "ขายสินค้าไม่สำเร็จ เนื่องจากสต๊อกไม่พอ");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "กรุณากรอกจำนวนสินค้าเป็นตัวเลข");
    }
    }//GEN-LAST:event_btnSaveSaleActionPerformed

    private void tblSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSaleMouseClicked

    private void cmbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductsActionPerformed
        loadSaleTable();
    }//GEN-LAST:event_cmbProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveSale;
    private javax.swing.JComboBox<String> cmbProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSale;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
